name: landing-zone
on:
  workflow_run:
    workflows: ["core-identity"]  # Dispara esse workflow ap처s a conclus찾o do antecessor (CORE-IDENTITY)
    types: [completed]


permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  Migration-Terraform-Backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Valida de a conclus찾o do workflow foi com status de success
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:        ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:  ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      # Download do tfstate da core-identity
      - name: Download core-identity state
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: core-identity
          run_id:  ${{ github.event.workflow_run.id }}
          name: tfstate-core
          path: core-identity

      - name: Azure Login (SPN bootstrap)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 1) Init LOCAL (ignora o backend azurerm declarado)
      - name: Terraform init (backend local)
        run: terraform -chdir=landing-zone init -backend=false

      - name: Terraform apply (cria Storage Account & container)
        run: terraform -chdir=landing-zone apply -auto-approve

      # 2) Captura outputs do SA criado
      - name: Read outputs
        id: tfout
        run: |
          SA=$(terraform -chdir=landing-zone output -raw state_sa_name)
          RG=$(terraform -chdir=landing-zone output -raw state_rg_name)
          echo "sa=$SA" >>"$GITHUB_OUTPUT"
          echo "rg=$RG" >>"$GITHUB_OUTPUT"

      # 3) MIGRA o state para o backend Azurerm  
      - name: Migrate landing-zone state to Azure Blob
        run: |
          terraform -chdir=landing-zone init \
            -backend-config="storage_account_name=${{ steps.tfout.outputs.sa }}" \
            -backend-config="container_name=tfstate-landing" \
            -backend-config="resource_group_name=${{ steps.tfout.outputs.rg }}" \
            -backend-config="key=landing.tfstate" \
            -migrate-state -force-copy

      # 4) Re-init s처 para gravar a config e aplicar (SEM copiar state de novo)
      - name: Reconfigure backend & apply
        run: |
          terraform -chdir=landing-zone init \
            -backend-config="storage_account_name=${{ steps.tfout.outputs.sa }}" \
            -backend-config="container_name=tfstate-landing" \
            -backend-config="resource_group_name=${{ steps.tfout.outputs.rg }}" \
            -backend-config="key=landing.tfstate" \
            -reconfigure
          terraform -chdir=landing-zone apply -auto-approve

